Users/aazhou/cleanup
Microsoft/vsts-sample-wit-custom-control pull request #5
Opened 2016-10-11 22:48 UTC by aaronyzhou

2016-10-11 23:48 UTC, cschleiden requested changes

2016-10-11 23:48 UTC, cschleiden commented on scripts/InputParser.ts
> +            return inputColors.slice(0,values.length);
spacing

2016-10-11 23:48 UTC, cschleiden commented on scripts/errorView.ts
> +        var table = $("<table></table>");
why a table? don't see any tabular data

2016-10-12 16:42 UTC, sferg-msft commented on scripts/errorView.ts
> +        var table = $("<table></table>");
+1

2016-10-12 18:16 UTC, aaronyzhou commented on scripts/InputParser.ts
> +            return inputColors.slice(0,values.length);
Fixed

2016-10-12 18:16 UTC, aaronyzhou commented on scripts/errorView.ts
> +        var table = $("<table></table>");
Fixed

2016-10-12 23:06 UTC, cschleiden approved these changes

2016-10-13 00:07 UTC, merged